NUMPY


In [1]:
import numpy as np


In [2]:
a=np.array([10,20,30,40,50,60])
a

array([10, 20, 30, 40, 50, 60])

In [4]:
a.dtype



dtype('int32')

In [6]:
a.shape

(6,)

In [7]:
a.ndim

1

In [8]:
a.size

6

In [9]:
a[0]

10

In [11]:
a[5]

60

In [24]:
a2d=np.array([[1,2,3,4,5,6],[10,20,30,40,50,60]])
a2d

array([[ 1,  2,  3,  4,  5,  6],
       [10, 20, 30, 40, 50, 60]])

In [25]:
a2d.shape

(2, 6)

In [26]:
a2d.ndim

2

In [28]:
a2d.dtype

dtype('int32')

In [38]:
a3d=np.array([[[1]]],dtype="float")

In [39]:
a3d

array([[[1.]]])

In [33]:
a2d[0][0]

1

In [34]:
a2d[0][5]

6

In [36]:
a2d[1][5]

60

filling


In [44]:
afull=np.full((3,5,4),7)

In [45]:
afull

array([[[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]]])

In [46]:
afull.ndim

3

In [47]:
azeros=np.zeros(5)

In [48]:
azeros

array([0., 0., 0., 0., 0.])

In [51]:
bzeros=np.zeros((5,6))
bzeros

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [52]:
bones=np.ones((5,6))
bones

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [53]:
e=np.empty((6,4))
e

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        2.33646845e-307],
       [1.33511018e-306, 1.33511969e-306, 6.23037996e-307,
        6.23053954e-307],
       [9.34609790e-307, 8.45593934e-307, 9.34600963e-307,
        9.34603000e-307],
       [1.78018403e-306, 8.90106955e-307, 1.60218491e-306,
        1.78018403e-306],
       [1.69119330e-306, 6.23054633e-307, 1.24610927e-306,
        1.05698817e-307],
       [1.11261638e-306, 1.33511562e-306, 2.22522596e-306,
        2.22522596e-306]])

In [55]:
arandom=np.random.random((5,2))
arandom

array([[0.31752862, 0.67638716],
       [0.30701253, 0.73010487],
       [0.34749973, 0.92825756],
       [0.67739282, 0.34516327],
       [0.20721599, 0.21713318]])

In [56]:
arandom.ndim

2

In [61]:
a_arrange=np.arange(10,100,5)
a_arrange

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [62]:
price=(90,999,8989)
price=np.array([90,999,8989])
type(price)

numpy.ndarray

In [63]:
s_array=np.array({"fathima","jopika","kiran","lubna",8,9889,999})
type(s_array)


numpy.ndarray

In [64]:
print(s_array.size)

1
